# Day 2
# key functions and Attributes in Pandas

In [3]:
import pandas as pd

In [24]:
# Column and index management 
df = pd.read_csv("emp.csv",delimiter=",",usecols=["eno","ename","doj"],header=0)

In [25]:
type(df)

pandas.core.frame.DataFrame

In [26]:
df

    eno    ename         doj
0    10    Amber  2018-05-14
1     2     Amar  2017-03-22
2     8    Sagar  2020-11-30
3     4   Thomas  2019-08-18
4     5     Jade  2021-02-10
5     6    Smith  2016-12-01
6     7   Robert  2023-06-25
7     3     Nick  2015-09-15
8     9    Naman  2020-01-20
9     1    Vikas  2017-10-03
10   11   Dennis  2024-01-05
11   12    Karan  2018-06-16
12   13   Simran  2019-12-19
13   14     Amit  2022-04-09
14   15     Neha  2021-07-22
15   16    Rahul  2016-03-28
16   17    Divya  2015-11-11
17   18   Rakesh  2020-09-04
18   19   Monica  2023-08-07
19   20     John  2018-10-29
20   21    Sneha  2022-12-14
21   22    David  2017-02-17
22   23    Anita  2019-05-21
23   24    Vinod  2016-07-30
24   25    Meena  2020-03-13
25   26    Harsh  2021-09-25
26   27   Kavita  2019-01-06
27   28    Mohan  2015-04-17
28   29    Priya  2023-02-11
29   30   Suresh  2018-09-09
30   31     Rani  2022-11-03
31   32     Ajay  2020-06-26
32   33    Nidhi  2016-05-12
33   34    Vivek  2017-07-31
34   35    Seema  2021-10-15
35   36     Ritu  2023-05-01
36   37    Kunal  2015-08-22
37   38     Alok  2019-03-02
38   39   Poonam  2022-02-05
39   40     Yash  2020-07-19
40   41     Nina  2018-12-28
41   42    Tarun  2021-01-09
42   43    Geeta  2017-11-14
43   44    Ashok  2016-06-08
44   45  Sanjana  2023-03-17
45   46    Manoj  2019-07-24
46   47    Payal  2015-10-10

In [20]:
# Select only eno and doj columns
columns_name = ['eno','doj']
df[columns_name]

    eno         doj
0    10  2018-05-14
1     2  2017-03-22
2     8  2020-11-30
3     4  2019-08-18
4     5  2021-02-10
5     6  2016-12-01
6     7  2023-06-25
7     3  2015-09-15
8     9  2020-01-20
9     1  2017-10-03
10   11  2024-01-05
11   12  2018-06-16
12   13  2019-12-19
13   14  2022-04-09
14   15  2021-07-22
15   16  2016-03-28
16   17  2015-11-11
17   18  2020-09-04
18   19  2023-08-07
19   20  2018-10-29
20   21  2022-12-14
21   22  2017-02-17
22   23  2019-05-21
23   24  2016-07-30
24   25  2020-03-13
25   26  2021-09-25
26   27  2019-01-06
27   28  2015-04-17
28   29  2023-02-11
29   30  2018-09-09
30   31  2022-11-03
31   32  2020-06-26
32   33  2016-05-12
33   34  2017-07-31
34   35  2021-10-15
35   36  2023-05-01
36   37  2015-08-22
37   38  2019-03-02
38   39  2022-02-05
39   40  2020-07-19
40   41  2018-12-28
41   42  2021-01-09
42   43  2017-11-14
43   44  2016-06-08
44   45  2023-03-17
45   46  2019-07-24
46   47  2015-10-10

In [27]:
# Select 4th row from the dataframe
row5  =df.iloc[4]

In [29]:
type(row5)

pandas.core.series.Series

In [15]:
df.head()

   eno   ename         doj
0   10   Amber  2018-05-14
1    2    Amar  2017-03-22
2    8   Sagar  2020-11-30
3    4  Thomas  2019-08-18
4    5    Jade  2021-02-10

In [32]:
# Select 3rd & 4th row from the dataframe
row2_3  =df.iloc[2:4]

In [34]:
type(row2_3)

pandas.core.frame.DataFrame

In [35]:
# set eno as index column
df1 = pd.read_csv("emp.csv",delimiter=",",header=0,index_col='eno')

In [36]:
df1

       ename  salary  deptno         doj
eno
10     Amber    1000      10  2018-05-14
2       Amar    1000      10  2017-03-22
8      Sagar    1000      20  2020-11-30
4     Thomas    1000      10  2019-08-18
5       Jade    2000      10  2021-02-10
6      Smith    1000      10  2016-12-01
7     Robert    3000      20  2023-06-25
3       Nick    1000      30  2015-09-15
9      Naman    4000      30  2020-01-20
1      Vikas    1000      30  2017-10-03
11    Dennis   41000      30  2024-01-05
12     Karan    2200      20  2018-06-16
13    Simran    1500      10  2019-12-19
14      Amit    2000      30  2022-04-09
15      Neha    1700      20  2021-07-22
16     Rahul    1200      10  2016-03-28
17     Divya    3000      30  2015-11-11
18    Rakesh    1800      10  2020-09-04
19    Monica    2500      20  2023-08-07
20      John    2300      30  2018-10-29
21     Sneha    2700      10  2022-12-14
22     David    1000      20  2017-02-17
23     Anita    1500      30  2019-05-21
24     Vinod    1800      10  2016-07-30
25     Meena    2000      20  2020-03-13
26     Harsh    1600      10  2021-09-25
27    Kavita    1400      30  2019-01-06
28     Mohan    1300      10  2015-04-17
29     Priya    1200      20  2023-02-11
30    Suresh    1100      10  2018-09-09
31      Rani    1900      20  2022-11-03
32      Ajay    2100      10  2020-06-26
33     Nidhi    2400      30  2016-05-12
34     Vivek    2000      20  2017-07-31
35     Seema    3000      10  2021-10-15
36      Ritu    3200      20  2023-05-01
37     Kunal    2800      30  2015-08-22
38      Alok    2700      10  2019-03-02
39    Poonam    2600      20  2022-02-05
40      Yash    2500      30  2020-07-19
41      Nina    2300      20  2018-12-28
42     Tarun    2200      10  2021-01-09
43     Geeta    2100      30  2017-11-14
44     Ashok    1900      10  2016-06-08
45   Sanjana    1800      20  2023-03-17
46     Manoj    1700      30  2019-07-24
47     Payal    1600      20  2015-10-10

In [38]:
# get me the record for eno=45
# select * from emp where eno=45
df1.loc[45]

ename        Sanjana
salary          1800
deptno            20
doj       2023-03-17
Name: 45, dtype: object

In [39]:
# get me the record for eno=45 to 47
# select * from emp where eno in ( 45,36,47)

df1.loc[45:47]

       ename  salary  deptno         doj
eno
45   Sanjana    1800      20  2023-03-17
46     Manoj    1700      30  2019-07-24
47     Payal    1600      20  2015-10-10

In [42]:
# get me the record for eno=45 to 47 and only columns with ename and doj
# select ename,doj from emp where eno in ( 45,36,47)
df1[['ename','doj']].loc[45:47]

       ename         doj
eno
45   Sanjana  2023-03-17
46     Manoj  2019-07-24
47     Payal  2015-10-10

In [43]:
# Read only eno , ename, doj as columns and first 10 rows
df = pd.read_csv("emp.csv",delimiter=",",usecols=["eno","ename","doj"],header=0,nrows=10)

In [44]:
df

   eno   ename         doj
0   10   Amber  2018-05-14
1    2    Amar  2017-03-22
2    8   Sagar  2020-11-30
3    4  Thomas  2019-08-18
4    5    Jade  2021-02-10
5    6   Smith  2016-12-01
6    7  Robert  2023-06-25
7    3    Nick  2015-09-15
8    9   Naman  2020-01-20
9    1   Vikas  2017-10-03

In [48]:
# Read only eno , ename, doj as columns and rows from 10 to 15 rows
df = pd.read_csv("emp.csv",delimiter=",",header=0,skiprows=10,nrows=5)

In [47]:
df

    1   Vikas   1000  30  2017-10-03
0  11  Dennis  41000  30  2024-01-05
1  12   Karan   2200  20  2018-06-16
2  13  Simran   1500  10  2019-12-19
3  14    Amit   2000  30  2022-04-09
4  15    Neha   1700  20  2021-07-22

In [55]:
df =  pd.read_csv("emp.csv")

In [56]:
# Ge the data types of the columns in the dataframe
df.dtypes

eno         int64
ename      object
salary    float64
deptno      int64
doj        object
dtype: object

In [60]:
# convert the datatype of eno from originally 'int' to 'object'
df =  pd.read_csv("emp.csv",dtype ={'eno':object})

In [63]:
df.dtypes

eno        object
ename      object
salary    float64
deptno      int64
doj        object
dtype: object

In [76]:
# convert the doj in to date format
df =  pd.read_csv("emp.csv",parse_dates=['doj'])

In [77]:
df.dtypes

eno                int64
ename             object
salary           float64
deptno             int64
doj       datetime64[ns]
dtype: object

In [79]:
# extract month, year, date
df['doj'].dt.month
df['doj'].dt.year

0     2018
1     2017
2     2020
3     2019
4     2021
5     2016
6     2023
7     2015
8     2020
9     2017
10    2024
11    2018
12    2019
13    2022
14    2021
15    2016
16    2015
17    2020
18    2023
19    2018
20    2022
21    2017
22    2019
23    2016
24    2020
25    2021
26    2019
27    2015
28    2023
29    2018
30    2022
31    2020
32    2016
33    2017
34    2021
35    2023
36    2015
37    2019
38    2022
39    2020
40    2018
41    2021
42    2017
43    2016
44    2023
45    2019
46    2015
Name: doj, dtype: int32

In [81]:
# low_memory=False ( when you want to read the whole file at once)
df =  pd.read_csv("emp.csv",parse_dates=['doj'],low_memory=False)

In [82]:
df

    eno    ename   salary  deptno        doj
0    10    Amber   1000.1      10 2018-05-14
1     2     Amar   1000.0      10 2017-03-22
2     8    Sagar   1000.0      20 2020-11-30
3     4   Thomas   1000.0      10 2019-08-18
4     5     Jade   2000.0      10 2021-02-10
5     6    Smith   1000.0      10 2016-12-01
6     7   Robert   3000.0      20 2023-06-25
7     3     Nick   1000.0      30 2015-09-15
8     9    Naman   4000.0      30 2020-01-20
9     1    Vikas   1000.0      30 2017-10-03
10   11   Dennis  41000.0      30 2024-01-05
11   12    Karan   2200.0      20 2018-06-16
12   13   Simran   1500.0      10 2019-12-19
13   14     Amit   2000.0      30 2022-04-09
14   15     Neha   1700.0      20 2021-07-22
15   16    Rahul   1200.0      10 2016-03-28
16   17    Divya   3000.0      30 2015-11-11
17   18   Rakesh   1800.0      10 2020-09-04
18   19   Monica   2500.0      20 2023-08-07
19   20     John   2300.0      30 2018-10-29
20   21    Sneha   2700.0      10 2022-12-14
21   22    David   1000.0      20 2017-02-17
22   23    Anita   1500.0      30 2019-05-21
23   24    Vinod   1800.0      10 2016-07-30
24   25    Meena   2000.0      20 2020-03-13
25   26    Harsh   1600.0      10 2021-09-25
26   27   Kavita   1400.0      30 2019-01-06
27   28    Mohan   1300.0      10 2015-04-17
28   29    Priya   1200.0      20 2023-02-11
29   30   Suresh   1100.0      10 2018-09-09
30   31     Rani   1900.0      20 2022-11-03
31   32     Ajay   2100.0      10 2020-06-26
32   33    Nidhi   2400.0      30 2016-05-12
33   34    Vivek   2000.0      20 2017-07-31
34   35    Seema   3000.0      10 2021-10-15
35   36     Ritu   3200.0      20 2023-05-01
36   37    Kunal   2800.0      30 2015-08-22
37   38     Alok   2700.0      10 2019-03-02
38   39   Poonam   2600.0      20 2022-02-05
39   40     Yash   2500.0      30 2020-07-19
40   41     Nina   2300.0      20 2018-12-28
41   42    Tarun   2200.0      10 2021-01-09
42   43    Geeta   2100.0      30 2017-11-14
43   44    Ashok   1900.0      10 2016-06-08
44   45  Sanjana   1800.0      20 2023-03-17
45   46    Manoj   1700.0      30 2019-07-24
46   47    Payal   1600.0      20 2015-10-10

In [92]:
# encoding
df =  pd.read_csv("emp.csv",encoding='utf-8')

In [93]:
df.dtypes

eno         int64
ename      object
salary    float64
deptno      int64
doj        object
dtype: object

# Filtering (Similar to where clause in SQL)

In [118]:
df =  pd.read_csv("emp.csv",parse_dates=['doj'])

In [104]:
df

    eno    ename   salary  deptno        doj
0    10    Amber   1000.1      10 2018-05-14
1     2     Amar   1000.0      10 2017-03-22
2     8    Sagar   1000.0      20 2020-11-30
3     4   Thomas   1000.0      10 2019-08-18
4     5     Jade   2000.0      10 2021-02-10
5     6    Smith   1000.0      10 2016-12-01
6     7   Robert   3000.0      20 2023-06-25
7     3     Nick   1000.0      30 2015-09-15
8     9    Naman   4000.0      30 2020-01-20
9     1    Vikas   1000.0      30 2017-10-03
10   11   Dennis  41000.0      30 2024-01-05
11   12    Karan   2200.0      20 2018-06-16
12   13   Simran   1500.0      10 2019-12-19
13   14     Amit   2000.0      30 2022-04-09
14   15     Neha   1700.0      20 2021-07-22
15   16    Rahul   1200.0      10 2016-03-28
16   17    Divya   3000.0      30 2015-11-11
17   18   Rakesh   1800.0      10 2020-09-04
18   19   Monica   2500.0      20 2023-08-07
19   20     John   2300.0      30 2018-10-29
20   21    Sneha   2700.0      10 2022-12-14
21   22    David   1000.0      20 2017-02-17
22   23    Anita   1500.0      30 2019-05-21
23   24    Vinod   1800.0      10 2016-07-30
24   25    Meena   2000.0      20 2020-03-13
25   26    Harsh   1600.0      10 2021-09-25
26   27   Kavita   1400.0      30 2019-01-06
27   28    Mohan   1300.0      10 2015-04-17
28   29    Priya   1200.0      20 2023-02-11
29   30   Suresh   1100.0      10 2018-09-09
30   31     Rani   1900.0      20 2022-11-03
31   32     Ajay   2100.0      10 2020-06-26
32   33    Nidhi   2400.0      30 2016-05-12
33   34    Vivek   2000.0      20 2017-07-31
34   35    Seema   3000.0      10 2021-10-15
35   36     Ritu   3200.0      20 2023-05-01
36   37    Kunal   2800.0      30 2015-08-22
37   38     Alok   2700.0      10 2019-03-02
38   39   Poonam   2600.0      20 2022-02-05
39   40     Yash   2500.0      30 2020-07-19
40   41     Nina   2300.0      20 2018-12-28
41   42    Tarun   2200.0      10 2021-01-09
42   43    Geeta   2100.0      30 2017-11-14
43   44    Ashok   1900.0      10 2016-06-08
44   45  Sanjana   1800.0      20 2023-03-17
45   46    Manoj   1700.0      30 2019-07-24
46   47    Payal   1600.0      20 2015-10-10

In [106]:
# Get me all the employees who are geting salary more than 3000 
# select * from emp where salary > 3000
salary_300 = df['salary'] > 3000

In [108]:
df[salary_300]

    eno   ename   salary  deptno        doj
8     9   Naman   4000.0      30 2020-01-20
10   11  Dennis  41000.0      30 2024-01-05
35   36    Ritu   3200.0      20 2023-05-01

In [125]:
# Get me all the employees who are geting salary more than 3000 and employees should belong from deptno=20
# select * from emp where salary > 3000 and deptno=20

salary_300 = df['salary'] > 3000
dept_10  = df['deptno'] == 20
final_filter = salary_300 & dept_10
df[final_filter]

    eno ename  salary  deptno        doj
35   36  Ritu  3200.0      20 2023-05-01

# Sorting ( arranging data in ascending/descending order)

In [128]:
# Sorting based on eno in ascending order
# select * from emp order by eno
df.sort_values(by='eno')
# or
# select * from emp order by eno asc
df.sort_values(by='eno',ascending=True)

    eno    ename   salary  deptno        doj
9     1    Vikas   1000.0      30 2017-10-03
1     2     Amar   1000.0      10 2017-03-22
7     3     Nick   1000.0      30 2015-09-15
3     4   Thomas   1000.0      10 2019-08-18
4     5     Jade   2000.0      10 2021-02-10
5     6    Smith   1000.0      10 2016-12-01
6     7   Robert   3000.0      20 2023-06-25
2     8    Sagar   1000.0      20 2020-11-30
8     9    Naman   4000.0      30 2020-01-20
0    10    Amber   1000.1      10 2018-05-14
10   11   Dennis  41000.0      30 2024-01-05
11   12    Karan   2200.0      20 2018-06-16
12   13   Simran   1500.0      10 2019-12-19
13   14     Amit   2000.0      30 2022-04-09
14   15     Neha   1700.0      20 2021-07-22
15   16    Rahul   1200.0      10 2016-03-28
16   17    Divya   3000.0      30 2015-11-11
17   18   Rakesh   1800.0      10 2020-09-04
18   19   Monica   2500.0      20 2023-08-07
19   20     John   2300.0      30 2018-10-29
20   21    Sneha   2700.0      10 2022-12-14
21   22    David   1000.0      20 2017-02-17
22   23    Anita   1500.0      30 2019-05-21
23   24    Vinod   1800.0      10 2016-07-30
24   25    Meena   2000.0      20 2020-03-13
25   26    Harsh   1600.0      10 2021-09-25
26   27   Kavita   1400.0      30 2019-01-06
27   28    Mohan   1300.0      10 2015-04-17
28   29    Priya   1200.0      20 2023-02-11
29   30   Suresh   1100.0      10 2018-09-09
30   31     Rani   1900.0      20 2022-11-03
31   32     Ajay   2100.0      10 2020-06-26
32   33    Nidhi   2400.0      30 2016-05-12
33   34    Vivek   2000.0      20 2017-07-31
34   35    Seema   3000.0      10 2021-10-15
35   36     Ritu   3200.0      20 2023-05-01
36   37    Kunal   2800.0      30 2015-08-22
37   38     Alok   2700.0      10 2019-03-02
38   39   Poonam   2600.0      20 2022-02-05
39   40     Yash   2500.0      30 2020-07-19
40   41     Nina   2300.0      20 2018-12-28
41   42    Tarun   2200.0      10 2021-01-09
42   43    Geeta   2100.0      30 2017-11-14
43   44    Ashok   1900.0      10 2016-06-08
44   45  Sanjana   1800.0      20 2023-03-17
45   46    Manoj   1700.0      30 2019-07-24
46   47    Payal   1600.0      20 2015-10-10

In [129]:
# Sorting based on eno in descending order
# select * from emp order by eno desc
df.sort_values(by='eno',ascending=False)

    eno    ename   salary  deptno        doj
46   47    Payal   1600.0      20 2015-10-10
45   46    Manoj   1700.0      30 2019-07-24
44   45  Sanjana   1800.0      20 2023-03-17
43   44    Ashok   1900.0      10 2016-06-08
42   43    Geeta   2100.0      30 2017-11-14
41   42    Tarun   2200.0      10 2021-01-09
40   41     Nina   2300.0      20 2018-12-28
39   40     Yash   2500.0      30 2020-07-19
38   39   Poonam   2600.0      20 2022-02-05
37   38     Alok   2700.0      10 2019-03-02
36   37    Kunal   2800.0      30 2015-08-22
35   36     Ritu   3200.0      20 2023-05-01
34   35    Seema   3000.0      10 2021-10-15
33   34    Vivek   2000.0      20 2017-07-31
32   33    Nidhi   2400.0      30 2016-05-12
31   32     Ajay   2100.0      10 2020-06-26
30   31     Rani   1900.0      20 2022-11-03
29   30   Suresh   1100.0      10 2018-09-09
28   29    Priya   1200.0      20 2023-02-11
27   28    Mohan   1300.0      10 2015-04-17
26   27   Kavita   1400.0      30 2019-01-06
25   26    Harsh   1600.0      10 2021-09-25
24   25    Meena   2000.0      20 2020-03-13
23   24    Vinod   1800.0      10 2016-07-30
22   23    Anita   1500.0      30 2019-05-21
21   22    David   1000.0      20 2017-02-17
20   21    Sneha   2700.0      10 2022-12-14
19   20     John   2300.0      30 2018-10-29
18   19   Monica   2500.0      20 2023-08-07
17   18   Rakesh   1800.0      10 2020-09-04
16   17    Divya   3000.0      30 2015-11-11
15   16    Rahul   1200.0      10 2016-03-28
14   15     Neha   1700.0      20 2021-07-22
13   14     Amit   2000.0      30 2022-04-09
12   13   Simran   1500.0      10 2019-12-19
11   12    Karan   2200.0      20 2018-06-16
10   11   Dennis  41000.0      30 2024-01-05
0    10    Amber   1000.1      10 2018-05-14
8     9    Naman   4000.0      30 2020-01-20
2     8    Sagar   1000.0      20 2020-11-30
6     7   Robert   3000.0      20 2023-06-25
5     6    Smith   1000.0      10 2016-12-01
4     5     Jade   2000.0      10 2021-02-10
3     4   Thomas   1000.0      10 2019-08-18
7     3     Nick   1000.0      30 2015-09-15
1     2     Amar   1000.0      10 2017-03-22
9     1    Vikas   1000.0      30 2017-10-03

In [130]:
# Sorting based on depnto in ascending and  salary in descending order
# select * from emp order by deptno asc,salary desc
df.sort_values(by=['deptno','salary'],ascending=[True,False])

    eno    ename   salary  deptno        doj
34   35    Seema   3000.0      10 2021-10-15
20   21    Sneha   2700.0      10 2022-12-14
37   38     Alok   2700.0      10 2019-03-02
41   42    Tarun   2200.0      10 2021-01-09
31   32     Ajay   2100.0      10 2020-06-26
4     5     Jade   2000.0      10 2021-02-10
43   44    Ashok   1900.0      10 2016-06-08
17   18   Rakesh   1800.0      10 2020-09-04
23   24    Vinod   1800.0      10 2016-07-30
25   26    Harsh   1600.0      10 2021-09-25
12   13   Simran   1500.0      10 2019-12-19
27   28    Mohan   1300.0      10 2015-04-17
15   16    Rahul   1200.0      10 2016-03-28
29   30   Suresh   1100.0      10 2018-09-09
0    10    Amber   1000.1      10 2018-05-14
1     2     Amar   1000.0      10 2017-03-22
3     4   Thomas   1000.0      10 2019-08-18
5     6    Smith   1000.0      10 2016-12-01
35   36     Ritu   3200.0      20 2023-05-01
6     7   Robert   3000.0      20 2023-06-25
38   39   Poonam   2600.0      20 2022-02-05
18   19   Monica   2500.0      20 2023-08-07
40   41     Nina   2300.0      20 2018-12-28
11   12    Karan   2200.0      20 2018-06-16
24   25    Meena   2000.0      20 2020-03-13
33   34    Vivek   2000.0      20 2017-07-31
30   31     Rani   1900.0      20 2022-11-03
44   45  Sanjana   1800.0      20 2023-03-17
14   15     Neha   1700.0      20 2021-07-22
46   47    Payal   1600.0      20 2015-10-10
28   29    Priya   1200.0      20 2023-02-11
2     8    Sagar   1000.0      20 2020-11-30
21   22    David   1000.0      20 2017-02-17
10   11   Dennis  41000.0      30 2024-01-05
8     9    Naman   4000.0      30 2020-01-20
16   17    Divya   3000.0      30 2015-11-11
36   37    Kunal   2800.0      30 2015-08-22
39   40     Yash   2500.0      30 2020-07-19
32   33    Nidhi   2400.0      30 2016-05-12
19   20     John   2300.0      30 2018-10-29
42   43    Geeta   2100.0      30 2017-11-14
13   14     Amit   2000.0      30 2022-04-09
45   46    Manoj   1700.0      30 2019-07-24
22   23    Anita   1500.0      30 2019-05-21
26   27   Kavita   1400.0      30 2019-01-06
7     3     Nick   1000.0      30 2015-09-15
9     1    Vikas   1000.0      30 2017-10-03

In [131]:
df

    eno    ename   salary  deptno        doj
0    10    Amber   1000.1      10 2018-05-14
1     2     Amar   1000.0      10 2017-03-22
2     8    Sagar   1000.0      20 2020-11-30
3     4   Thomas   1000.0      10 2019-08-18
4     5     Jade   2000.0      10 2021-02-10
5     6    Smith   1000.0      10 2016-12-01
6     7   Robert   3000.0      20 2023-06-25
7     3     Nick   1000.0      30 2015-09-15
8     9    Naman   4000.0      30 2020-01-20
9     1    Vikas   1000.0      30 2017-10-03
10   11   Dennis  41000.0      30 2024-01-05
11   12    Karan   2200.0      20 2018-06-16
12   13   Simran   1500.0      10 2019-12-19
13   14     Amit   2000.0      30 2022-04-09
14   15     Neha   1700.0      20 2021-07-22
15   16    Rahul   1200.0      10 2016-03-28
16   17    Divya   3000.0      30 2015-11-11
17   18   Rakesh   1800.0      10 2020-09-04
18   19   Monica   2500.0      20 2023-08-07
19   20     John   2300.0      30 2018-10-29
20   21    Sneha   2700.0      10 2022-12-14
21   22    David   1000.0      20 2017-02-17
22   23    Anita   1500.0      30 2019-05-21
23   24    Vinod   1800.0      10 2016-07-30
24   25    Meena   2000.0      20 2020-03-13
25   26    Harsh   1600.0      10 2021-09-25
26   27   Kavita   1400.0      30 2019-01-06
27   28    Mohan   1300.0      10 2015-04-17
28   29    Priya   1200.0      20 2023-02-11
29   30   Suresh   1100.0      10 2018-09-09
30   31     Rani   1900.0      20 2022-11-03
31   32     Ajay   2100.0      10 2020-06-26
32   33    Nidhi   2400.0      30 2016-05-12
33   34    Vivek   2000.0      20 2017-07-31
34   35    Seema   3000.0      10 2021-10-15
35   36     Ritu   3200.0      20 2023-05-01
36   37    Kunal   2800.0      30 2015-08-22
37   38     Alok   2700.0      10 2019-03-02
38   39   Poonam   2600.0      20 2022-02-05
39   40     Yash   2500.0      30 2020-07-19
40   41     Nina   2300.0      20 2018-12-28
41   42    Tarun   2200.0      10 2021-01-09
42   43    Geeta   2100.0      30 2017-11-14
43   44    Ashok   1900.0      10 2016-06-08
44   45  Sanjana   1800.0      20 2023-03-17
45   46    Manoj   1700.0      30 2019-07-24
46   47    Payal   1600.0      20 2015-10-10

In [132]:
# sort_index
df =  pd.read_csv("emp.csv",parse_dates=['doj'],index_col='eno')

In [134]:
df.sort_index()

       ename   salary  deptno        doj
eno
1      Vikas   1000.0      30 2017-10-03
2       Amar   1000.0      10 2017-03-22
3       Nick   1000.0      30 2015-09-15
4     Thomas   1000.0      10 2019-08-18
5       Jade   2000.0      10 2021-02-10
6      Smith   1000.0      10 2016-12-01
7     Robert   3000.0      20 2023-06-25
8      Sagar   1000.0      20 2020-11-30
9      Naman   4000.0      30 2020-01-20
10     Amber   1000.1      10 2018-05-14
11    Dennis  41000.0      30 2024-01-05
12     Karan   2200.0      20 2018-06-16
13    Simran   1500.0      10 2019-12-19
14      Amit   2000.0      30 2022-04-09
15      Neha   1700.0      20 2021-07-22
16     Rahul   1200.0      10 2016-03-28
17     Divya   3000.0      30 2015-11-11
18    Rakesh   1800.0      10 2020-09-04
19    Monica   2500.0      20 2023-08-07
20      John   2300.0      30 2018-10-29
21     Sneha   2700.0      10 2022-12-14
22     David   1000.0      20 2017-02-17
23     Anita   1500.0      30 2019-05-21
24     Vinod   1800.0      10 2016-07-30
25     Meena   2000.0      20 2020-03-13
26     Harsh   1600.0      10 2021-09-25
27    Kavita   1400.0      30 2019-01-06
28     Mohan   1300.0      10 2015-04-17
29     Priya   1200.0      20 2023-02-11
30    Suresh   1100.0      10 2018-09-09
31      Rani   1900.0      20 2022-11-03
32      Ajay   2100.0      10 2020-06-26
33     Nidhi   2400.0      30 2016-05-12
34     Vivek   2000.0      20 2017-07-31
35     Seema   3000.0      10 2021-10-15
36      Ritu   3200.0      20 2023-05-01
37     Kunal   2800.0      30 2015-08-22
38      Alok   2700.0      10 2019-03-02
39    Poonam   2600.0      20 2022-02-05
40      Yash   2500.0      30 2020-07-19
41      Nina   2300.0      20 2018-12-28
42     Tarun   2200.0      10 2021-01-09
43     Geeta   2100.0      30 2017-11-14
44     Ashok   1900.0      10 2016-06-08
45   Sanjana   1800.0      20 2023-03-17
46     Manoj   1700.0      30 2019-07-24
47     Payal   1600.0      20 2015-10-10

In [137]:
# Doubt session
df =  pd.read_csv("emp.csv",parse_dates=['doj'])

In [140]:
# Sort data by default index in descending order
df.sort_index(ascending=False)

    eno    ename   salary  deptno        doj
46   47    Payal   1600.0      20 2015-10-10
45   46    Manoj   1700.0      30 2019-07-24
44   45  Sanjana   1800.0      20 2023-03-17
43   44    Ashok   1900.0      10 2016-06-08
42   43    Geeta   2100.0      30 2017-11-14
41   42    Tarun   2200.0      10 2021-01-09
40   41     Nina   2300.0      20 2018-12-28
39   40     Yash   2500.0      30 2020-07-19
38   39   Poonam   2600.0      20 2022-02-05
37   38     Alok   2700.0      10 2019-03-02
36   37    Kunal   2800.0      30 2015-08-22
35   36     Ritu   3200.0      20 2023-05-01
34   35    Seema   3000.0      10 2021-10-15
33   34    Vivek   2000.0      20 2017-07-31
32   33    Nidhi   2400.0      30 2016-05-12
31   32     Ajay   2100.0      10 2020-06-26
30   31     Rani   1900.0      20 2022-11-03
29   30   Suresh   1100.0      10 2018-09-09
28   29    Priya   1200.0      20 2023-02-11
27   28    Mohan   1300.0      10 2015-04-17
26   27   Kavita   1400.0      30 2019-01-06
25   26    Harsh   1600.0      10 2021-09-25
24   25    Meena   2000.0      20 2020-03-13
23   24    Vinod   1800.0      10 2016-07-30
22   23    Anita   1500.0      30 2019-05-21
21   22    David   1000.0      20 2017-02-17
20   21    Sneha   2700.0      10 2022-12-14
19   20     John   2300.0      30 2018-10-29
18   19   Monica   2500.0      20 2023-08-07
17   18   Rakesh   1800.0      10 2020-09-04
16   17    Divya   3000.0      30 2015-11-11
15   16    Rahul   1200.0      10 2016-03-28
14   15     Neha   1700.0      20 2021-07-22
13   14     Amit   2000.0      30 2022-04-09
12   13   Simran   1500.0      10 2019-12-19
11   12    Karan   2200.0      20 2018-06-16
10   11   Dennis  41000.0      30 2024-01-05
9     1    Vikas   1000.0      30 2017-10-03
8     9    Naman   4000.0      30 2020-01-20
7     3     Nick   1000.0      30 2015-09-15
6     7   Robert   3000.0      20 2023-06-25
5     6    Smith   1000.0      10 2016-12-01
4     5     Jade   2000.0      10 2021-02-10
3     4   Thomas   1000.0      10 2019-08-18
2     8    Sagar   1000.0      20 2020-11-30
1     2     Amar   1000.0      10 2017-03-22
0    10    Amber   1000.1      10 2018-05-14

In [141]:
df =  pd.read_csv("emp.csv",parse_dates=['doj'],index_col='eno')

In [145]:
df.dtypes

ename             object
salary           float64
deptno             int64
doj       datetime64[ns]
dtype: object

In [143]:
# Arranging the data in ascending order of my own created index column ( eno)
df.sort_index(ascending=True)

       ename   salary  deptno        doj
eno
1      Vikas   1000.0      30 2017-10-03
2       Amar   1000.0      10 2017-03-22
3       Nick   1000.0      30 2015-09-15
4     Thomas   1000.0      10 2019-08-18
5       Jade   2000.0      10 2021-02-10
6      Smith   1000.0      10 2016-12-01
7     Robert   3000.0      20 2023-06-25
8      Sagar   1000.0      20 2020-11-30
9      Naman   4000.0      30 2020-01-20
10     Amber   1000.1      10 2018-05-14
11    Dennis  41000.0      30 2024-01-05
12     Karan   2200.0      20 2018-06-16
13    Simran   1500.0      10 2019-12-19
14      Amit   2000.0      30 2022-04-09
15      Neha   1700.0      20 2021-07-22
16     Rahul   1200.0      10 2016-03-28
17     Divya   3000.0      30 2015-11-11
18    Rakesh   1800.0      10 2020-09-04
19    Monica   2500.0      20 2023-08-07
20      John   2300.0      30 2018-10-29
21     Sneha   2700.0      10 2022-12-14
22     David   1000.0      20 2017-02-17
23     Anita   1500.0      30 2019-05-21
24     Vinod   1800.0      10 2016-07-30
25     Meena   2000.0      20 2020-03-13
26     Harsh   1600.0      10 2021-09-25
27    Kavita   1400.0      30 2019-01-06
28     Mohan   1300.0      10 2015-04-17
29     Priya   1200.0      20 2023-02-11
30    Suresh   1100.0      10 2018-09-09
31      Rani   1900.0      20 2022-11-03
32      Ajay   2100.0      10 2020-06-26
33     Nidhi   2400.0      30 2016-05-12
34     Vivek   2000.0      20 2017-07-31
35     Seema   3000.0      10 2021-10-15
36      Ritu   3200.0      20 2023-05-01
37     Kunal   2800.0      30 2015-08-22
38      Alok   2700.0      10 2019-03-02
39    Poonam   2600.0      20 2022-02-05
40      Yash   2500.0      30 2020-07-19
41      Nina   2300.0      20 2018-12-28
42     Tarun   2200.0      10 2021-01-09
43     Geeta   2100.0      30 2017-11-14
44     Ashok   1900.0      10 2016-06-08
45   Sanjana   1800.0      20 2023-03-17
46     Manoj   1700.0      30 2019-07-24
47     Payal   1600.0      20 2015-10-10

In [144]:
# Arranging the data in descending  order of my own created index column ( eno)
df.sort_index(ascending=False)

       ename   salary  deptno        doj
eno
47     Payal   1600.0      20 2015-10-10
46     Manoj   1700.0      30 2019-07-24
45   Sanjana   1800.0      20 2023-03-17
44     Ashok   1900.0      10 2016-06-08
43     Geeta   2100.0      30 2017-11-14
42     Tarun   2200.0      10 2021-01-09
41      Nina   2300.0      20 2018-12-28
40      Yash   2500.0      30 2020-07-19
39    Poonam   2600.0      20 2022-02-05
38      Alok   2700.0      10 2019-03-02
37     Kunal   2800.0      30 2015-08-22
36      Ritu   3200.0      20 2023-05-01
35     Seema   3000.0      10 2021-10-15
34     Vivek   2000.0      20 2017-07-31
33     Nidhi   2400.0      30 2016-05-12
32      Ajay   2100.0      10 2020-06-26
31      Rani   1900.0      20 2022-11-03
30    Suresh   1100.0      10 2018-09-09
29     Priya   1200.0      20 2023-02-11
28     Mohan   1300.0      10 2015-04-17
27    Kavita   1400.0      30 2019-01-06
26     Harsh   1600.0      10 2021-09-25
25     Meena   2000.0      20 2020-03-13
24     Vinod   1800.0      10 2016-07-30
23     Anita   1500.0      30 2019-05-21
22     David   1000.0      20 2017-02-17
21     Sneha   2700.0      10 2022-12-14
20      John   2300.0      30 2018-10-29
19    Monica   2500.0      20 2023-08-07
18    Rakesh   1800.0      10 2020-09-04
17     Divya   3000.0      30 2015-11-11
16     Rahul   1200.0      10 2016-03-28
15      Neha   1700.0      20 2021-07-22
14      Amit   2000.0      30 2022-04-09
13    Simran   1500.0      10 2019-12-19
12     Karan   2200.0      20 2018-06-16
11    Dennis  41000.0      30 2024-01-05
10     Amber   1000.1      10 2018-05-14
9      Naman   4000.0      30 2020-01-20
8      Sagar   1000.0      20 2020-11-30
7     Robert   3000.0      20 2023-06-25
6      Smith   1000.0      10 2016-12-01
5       Jade   2000.0      10 2021-02-10
4     Thomas   1000.0      10 2019-08-18
3       Nick   1000.0      30 2015-09-15
2       Amar   1000.0      10 2017-03-22
1      Vikas   1000.0      30 2017-10-03

In [157]:
# get me all the employees who joined in year 2018
df =  pd.read_csv("emp.csv",parse_dates=['doj'])
year_2018 = df['doj'].dt.year == 2018
df[year_2018]

    eno   ename  salary  deptno        doj
0    10   Amber  1000.1      10 2018-05-14
11   12   Karan  2200.0      20 2018-06-16
19   20    John  2300.0      30 2018-10-29
29   30  Suresh  1100.0      10 2018-09-09
40   41    Nina  2300.0      20 2018-12-28

In [154]:
df.dtypes

eno                int64
ename             object
salary           float64
deptno             int64
doj       datetime64[ns]
dtype: object