Day 2

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('emp.csv',delimiter=',',usecols=['eno','ename','doj'])

In [4]:
df

    eno    ename         doj
0    10    Amber  2018-05-14
1     2     Amar  2017-03-22
2     8    Sagar  2020-11-30
3     4   Thomas  2019-08-18
4     5     Jade  2021-02-10
5     6    Smith  2016-12-01
6     7   Robert  2023-06-25
7     3     Nick  2015-09-15
8     9    Naman  2020-01-20
9     1    Vikas  2017-10-03
10   11   Dennis  2024-01-05
11   12    Karan  2018-06-16
12   13   Simran  2019-12-19
13   14     Amit  2022-04-09
14   15     Neha  2021-07-22
15   16    Rahul  2016-03-28
16   17    Divya  2015-11-11
17   18   Rakesh  2020-09-04
18   19   Monica  2023-08-07
19   20     John  2018-10-29
20   21    Sneha  2022-12-14
21   22    David  2017-02-17
22   23    Anita  2019-05-21
23   24    Vinod  2016-07-30
24   25    Meena  2020-03-13
25   26    Harsh  2021-09-25
26   27   Kavita  2019-01-06
27   28    Mohan  2015-04-17
28   29    Priya  2023-02-11
29   30   Suresh  2018-09-09
30   31     Rani  2022-11-03
31   32     Ajay  2020-06-26
32   33    Nidhi  2016-05-12
33   34    Vivek  2017-07-31
34   35    Seema  2021-10-15
35   36     Ritu  2023-05-01
36   37    Kunal  2015-08-22
37   38     Alok  2019-03-02
38   39   Poonam  2022-02-05
39   40     Yash  2020-07-19
40   41     Nina  2018-12-28
41   42    Tarun  2021-01-09
42   43    Geeta  2017-11-14
43   44    Ashok  2016-06-08
44   45  Sanjana  2023-03-17
45   46    Manoj  2019-07-24
46   47    Payal  2015-10-10

In [5]:
col_name=['eno','ename']
df[col_name]

    eno    ename
0    10    Amber
1     2     Amar
2     8    Sagar
3     4   Thomas
4     5     Jade
5     6    Smith
6     7   Robert
7     3     Nick
8     9    Naman
9     1    Vikas
10   11   Dennis
11   12    Karan
12   13   Simran
13   14     Amit
14   15     Neha
15   16    Rahul
16   17    Divya
17   18   Rakesh
18   19   Monica
19   20     John
20   21    Sneha
21   22    David
22   23    Anita
23   24    Vinod
24   25    Meena
25   26    Harsh
26   27   Kavita
27   28    Mohan
28   29    Priya
29   30   Suresh
30   31     Rani
31   32     Ajay
32   33    Nidhi
33   34    Vivek
34   35    Seema
35   36     Ritu
36   37    Kunal
37   38     Alok
38   39   Poonam
39   40     Yash
40   41     Nina
41   42    Tarun
42   43    Geeta
43   44    Ashok
44   45  Sanjana
45   46    Manoj
46   47    Payal

In [6]:
df.head()

   eno   ename         doj
0   10   Amber  2018-05-14
1    2    Amar  2017-03-22
2    8   Sagar  2020-11-30
3    4  Thomas  2019-08-18
4    5    Jade  2021-02-10

In [7]:
index1=df.iloc[4]

In [8]:
type(index1)

pandas.core.series.Series

In [9]:
index1

eno               5
ename          Jade
doj      2021-02-10
Name: 4, dtype: object

In [10]:
df.iloc[:2]

   eno  ename         doj
0   10  Amber  2018-05-14
1    2   Amar  2017-03-22

In [11]:
df.loc[:2]

   eno  ename         doj
0   10  Amber  2018-05-14
1    2   Amar  2017-03-22
2    8  Sagar  2020-11-30

In [12]:
df=pd.read_csv('emp.csv',delimiter=',',header=0,index_col='eno')

In [13]:
df

       ename  salary  deptno         doj
eno
10     Amber    1000      10  2018-05-14
2       Amar    1000      10  2017-03-22
8      Sagar    1000      20  2020-11-30
4     Thomas    1000      10  2019-08-18
5       Jade    2000      10  2021-02-10
6      Smith    1000      10  2016-12-01
7     Robert    3000      20  2023-06-25
3       Nick    1000      30  2015-09-15
9      Naman    4000      30  2020-01-20
1      Vikas    1000      30  2017-10-03
11    Dennis   41000      30  2024-01-05
12     Karan    2200      20  2018-06-16
13    Simran    1500      10  2019-12-19
14      Amit    2000      30  2022-04-09
15      Neha    1700      20  2021-07-22
16     Rahul    1200      10  2016-03-28
17     Divya    3000      30  2015-11-11
18    Rakesh    1800      10  2020-09-04
19    Monica    2500      20  2023-08-07
20      John    2300      30  2018-10-29
21     Sneha    2700      10  2022-12-14
22     David    1000      20  2017-02-17
23     Anita    1500      30  2019-05-21
24     Vinod    1800      10  2016-07-30
25     Meena    2000      20  2020-03-13
26     Harsh    1600      10  2021-09-25
27    Kavita    1400      30  2019-01-06
28     Mohan    1300      10  2015-04-17
29     Priya    1200      20  2023-02-11
30    Suresh    1100      10  2018-09-09
31      Rani    1900      20  2022-11-03
32      Ajay    2100      10  2020-06-26
33     Nidhi    2400      30  2016-05-12
34     Vivek    2000      20  2017-07-31
35     Seema    3000      10  2021-10-15
36      Ritu    3200      20  2023-05-01
37     Kunal    2800      30  2015-08-22
38      Alok    2700      10  2019-03-02
39    Poonam    2600      20  2022-02-05
40      Yash    2500      30  2020-07-19
41      Nina    2300      20  2018-12-28
42     Tarun    2200      10  2021-01-09
43     Geeta    2100      30  2017-11-14
44     Ashok    1900      10  2016-06-08
45   Sanjana    1800      20  2023-03-17
46     Manoj    1700      30  2019-07-24
47     Payal    1600      20  2015-10-10

In [14]:
df.loc[:2]

     ename  salary  deptno         doj
eno
10   Amber    1000      10  2018-05-14
2     Amar    1000      10  2017-03-22

In [15]:
df.loc[45:47]

       ename  salary  deptno         doj
eno
45   Sanjana    1800      20  2023-03-17
46     Manoj    1700      30  2019-07-24
47     Payal    1600      20  2015-10-10

In [16]:
df.loc[10:15]

      ename  salary  deptno         doj
eno
10    Amber    1000      10  2018-05-14
2      Amar    1000      10  2017-03-22
8     Sagar    1000      20  2020-11-30
4    Thomas    1000      10  2019-08-18
5      Jade    2000      10  2021-02-10
6     Smith    1000      10  2016-12-01
7    Robert    3000      20  2023-06-25
3      Nick    1000      30  2015-09-15
9     Naman    4000      30  2020-01-20
1     Vikas    1000      30  2017-10-03
11   Dennis   41000      30  2024-01-05
12    Karan    2200      20  2018-06-16
13   Simran    1500      10  2019-12-19
14     Amit    2000      30  2022-04-09
15     Neha    1700      20  2021-07-22

In [17]:
df.loc[45:47]

       ename  salary  deptno         doj
eno
45   Sanjana    1800      20  2023-03-17
46     Manoj    1700      30  2019-07-24
47     Payal    1600      20  2015-10-10

In [18]:
df.iloc[45:47]

     ename  salary  deptno         doj
eno
46   Manoj    1700      30  2019-07-24
47   Payal    1600      20  2015-10-10

In [19]:
df[['ename','doj']]

       ename         doj
eno
10     Amber  2018-05-14
2       Amar  2017-03-22
8      Sagar  2020-11-30
4     Thomas  2019-08-18
5       Jade  2021-02-10
6      Smith  2016-12-01
7     Robert  2023-06-25
3       Nick  2015-09-15
9      Naman  2020-01-20
1      Vikas  2017-10-03
11    Dennis  2024-01-05
12     Karan  2018-06-16
13    Simran  2019-12-19
14      Amit  2022-04-09
15      Neha  2021-07-22
16     Rahul  2016-03-28
17     Divya  2015-11-11
18    Rakesh  2020-09-04
19    Monica  2023-08-07
20      John  2018-10-29
21     Sneha  2022-12-14
22     David  2017-02-17
23     Anita  2019-05-21
24     Vinod  2016-07-30
25     Meena  2020-03-13
26     Harsh  2021-09-25
27    Kavita  2019-01-06
28     Mohan  2015-04-17
29     Priya  2023-02-11
30    Suresh  2018-09-09
31      Rani  2022-11-03
32      Ajay  2020-06-26
33     Nidhi  2016-05-12
34     Vivek  2017-07-31
35     Seema  2021-10-15
36      Ritu  2023-05-01
37     Kunal  2015-08-22
38      Alok  2019-03-02
39    Poonam  2022-02-05
40      Yash  2020-07-19
41      Nina  2018-12-28
42     Tarun  2021-01-09
43     Geeta  2017-11-14
44     Ashok  2016-06-08
45   Sanjana  2023-03-17
46     Manoj  2019-07-24
47     Payal  2015-10-10

In [20]:
df[['ename','doj']].loc[45:47]

       ename         doj
eno
45   Sanjana  2023-03-17
46     Manoj  2019-07-24
47     Payal  2015-10-10

In [22]:
df=pd.read_csv('emp.csv',delimiter=',',header=0,nrows=10)

In [23]:
df

   eno   ename  salary  deptno         doj
0   10   Amber    1000      10  2018-05-14
1    2    Amar    1000      10  2017-03-22
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      10  2019-08-18
4    5    Jade    2000      10  2021-02-10
5    6   Smith    1000      10  2016-12-01
6    7  Robert    3000      20  2023-06-25
7    3    Nick    1000      30  2015-09-15
8    9   Naman    4000      30  2020-01-20
9    1   Vikas    1000      30  2017-10-03

In [31]:
df=pd.read_csv('emp.csv',delimiter=',',header=0,skiprows=10,nrows=5)

In [32]:
df

    1   Vikas   1000  30  2017-10-03
0  11  Dennis  41000  30  2024-01-05
1  12   Karan   2200  20  2018-06-16
2  13  Simran   1500  10  2019-12-19
3  14    Amit   2000  30  2022-04-09
4  15    Neha   1700  20  2021-07-22

In [34]:
df = pd.read_csv('emp.csv', delimiter=',', skiprows=range(1, 11), nrows=5)

In [35]:
df

   eno   ename  salary  deptno         doj
0   11  Dennis   41000      30  2024-01-05
1   12   Karan    2200      20  2018-06-16
2   13  Simran    1500      10  2019-12-19
3   14    Amit    2000      30  2022-04-09
4   15    Neha    1700      20  2021-07-22

In [37]:
df = pd.read_csv( 'emp.csv',delimiter=',',skiprows=range(1, 11),nrows=5,usecols=['eno', 'ename', 'salary'] )

In [38]:
df

   eno   ename  salary
0   11  Dennis   41000
1   12   Karan    2200
2   13  Simran    1500
3   14    Amit    2000
4   15    Neha    1700

In [39]:
df.dtypes

eno        int64
ename     object
salary     int64
dtype: object

In [40]:
df = pd.read_csv( 'emp.csv',delimiter=',',skiprows=range(1, 11),nrows=5,usecols=[0,2,3] )

In [41]:
df

   eno  salary  deptno
0   11   41000      30
1   12    2200      20
2   13    1500      10
3   14    2000      30
4   15    1700      20

In [42]:
df.dtypes

eno       int64
salary    int64
deptno    int64
dtype: object

In [43]:
df=pd.read_csv('emp.csv',dtype={'eno':object})

In [44]:
df.dtypes

eno       object
ename     object
salary     int64
deptno     int64
doj       object
dtype: object

In [73]:
df=pd.read_csv('emp.csv',parse_dates=['doj'])

In [74]:
df.dtypes

eno                int64
ename             object
salary             int64
deptno             int64
doj       datetime64[ns]
dtype: object

In [78]:
df= pd.to_datetime(df['doj'], format='%Y-%m-%d')

In [79]:
df

0    2018-05-14
1    2017-03-22
2    2020-11-30
3    2019-08-18
4    2021-02-10
5    2016-12-01
6    2023-06-25
7    2015-09-15
8    2020-01-20
9    2017-10-03
10   2024-01-05
11   2018-06-16
12   2019-12-19
13   2022-04-09
14   2021-07-22
15   2016-03-28
16   2015-11-11
17   2020-09-04
18   2023-08-07
19   2018-10-29
20   2022-12-14
21   2017-02-17
22   2019-05-21
23   2016-07-30
24   2020-03-13
25   2021-09-25
26   2019-01-06
27   2015-04-17
28   2023-02-11
29   2018-09-09
30   2022-11-03
31   2020-06-26
32   2016-05-12
33   2017-07-31
34   2021-10-15
35   2023-05-01
36   2015-08-22
37   2019-03-02
38   2022-02-05
39   2020-07-19
40   2018-12-28
41   2021-01-09
42   2017-11-14
43   2016-06-08
44   2023-03-17
45   2019-07-24
46   2015-10-10
Name: doj, dtype: datetime64[ns]

In [80]:
df.dt.month

0      5
1      3
2     11
3      8
4      2
5     12
6      6
7      9
8      1
9     10
10     1
11     6
12    12
13     4
14     7
15     3
16    11
17     9
18     8
19    10
20    12
21     2
22     5
23     7
24     3
25     9
26     1
27     4
28     2
29     9
30    11
31     6
32     5
33     7
34    10
35     5
36     8
37     3
38     2
39     7
40    12
41     1
42    11
43     6
44     3
45     7
46    10
Name: doj, dtype: int32

In [3]:
for i in pd.read_csv('emp.csv',chunksize=10):
    print(i)

   eno   ename  salary  deptno         doj
0   10   Amber    1000      10  2018-05-14
1    2    Amar    1000      10  2017-03-22
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      10  2019-08-18
4    5    Jade    2000      10  2021-02-10
5    6   Smith    1000      10  2016-12-01
6    7  Robert    3000      20  2023-06-25
7    3    Nick    1000      30  2015-09-15
8    9   Naman    4000      30  2020-01-20
9    1   Vikas    1000      30  2017-10-03
    eno   ename  salary  deptno         doj
10   11  Dennis   41000      30  2024-01-05
11   12   Karan    2200      20  2018-06-16
12   13  Simran    1500      10  2019-12-19
13   14    Amit    2000      30  2022-04-09
14   15    Neha    1700      20  2021-07-22
15   16   Rahul    1200      10  2016-03-28
16   17   Divya    3000      30  2015-11-11
17   18  Rakesh    1800      10  2020-09-04
18   19  Monica    2500      20  2023-08-07
19   20    John    2300      30  2018-10-29
    eno   ename  salary  deptno         doj
20   21   Sneha    2700      10  2022-12-14
21   22   David    1000      20  2017-02-17
22   23   Anita    1500      30  2019-05-21
23   24   Vinod    1800      10  2016-07-30
24   25   Meena    2000      20  2020-03-13
25   26   Harsh    1600      10  2021-09-25
26   27  Kavita    1400      30  2019-01-06
27   28   Mohan    1300      10  2015-04-17
28   29   Priya    1200      20  2023-02-11
29   30  Suresh    1100      10  2018-09-09
    eno   ename  salary  deptno         doj
30   31    Rani    1900      20  2022-11-03
31   32    Ajay    2100      10  2020-06-26
32   33   Nidhi    2400      30  2016-05-12
33   34   Vivek    2000      20  2017-07-31
34   35   Seema    3000      10  2021-10-15
35   36    Ritu    3200      20  2023-05-01
36   37   Kunal    2800      30  2015-08-22
37   38    Alok    2700      10  2019-03-02
38   39  Poonam    2600      20  2022-02-05
39   40    Yash    2500      30  2020-07-19
    eno    ename  salary  deptno         doj
40   41     Nina    2300      20  2018-12-28
41   42    Tarun    2200      10  2021-01-09
42   43    Geeta    2100      30  2017-11-14
43   44    Ashok    1900      10  2016-06-08
44   45  Sanjana    1800      20  2023-03-17
45   46    Manoj    1700      30  2019-07-24
46   47    Payal    1600      20  2015-10-10

In [4]:
import chardet

with open("emp.csv", "rb") as f:
    result = chardet.detect(f.read(10000))

print(result)

ModuleNotFoundError: No module named 'chardet'